USE [master]
GO
/****** Object:  Database [PeopleDb]    Script Date: 17/10/2020 5:16:10 ******/
CREATE DATABASE [PeopleDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PeopleDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER01\MSSQL\DATA\PeopleDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PeopleDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER01\MSSQL\DATA\PeopleDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [PeopleDb] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PeopleDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PeopleDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PeopleDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PeopleDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PeopleDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PeopleDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [PeopleDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PeopleDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PeopleDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PeopleDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PeopleDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PeopleDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PeopleDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PeopleDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PeopleDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PeopleDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PeopleDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PeopleDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PeopleDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PeopleDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PeopleDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PeopleDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PeopleDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PeopleDb] SET RECOVERY FULL 
GO
ALTER DATABASE [PeopleDb] SET  MULTI_USER 
GO
ALTER DATABASE [PeopleDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PeopleDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PeopleDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PeopleDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PeopleDb] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'PeopleDb', N'ON'
GO
ALTER DATABASE [PeopleDb] SET QUERY_STORE = OFF
GO
USE [PeopleDb]
GO
/****** Object:  User [igor]    Script Date: 17/10/2020 5:16:10 ******/
CREATE USER [sa] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[affiliations]    Script Date: 17/10/2020 5:16:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[affiliations](
	[_id] [int] IDENTITY(1,1) NOT NULL,
	[id] [nvarchar](10) NOT NULL,
	[since] [int] NULL,
	[organization_id] [int] NULL,
	[role_id] [int] NULL,
	[person_id] [int] NULL,
 CONSTRAINT [PK_4c5daaa050b6e2d415a884e04f1] PRIMARY KEY CLUSTERED 
(
	[_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_454335765b4671b2e94313ec4b3] UNIQUE NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[organizations]    Script Date: 17/10/2020 5:16:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[organizations](
	[_id] [int] IDENTITY(1,1) NOT NULL,
	[id] [nvarchar](10) NOT NULL,
	[name] [nvarchar](50) NOT NULL,
	[address] [nvarchar](50) NULL,
	[parent_id] [int] NULL,
 CONSTRAINT [PK_0f46d1fee63f4726a41d4522689] PRIMARY KEY CLUSTERED 
(
	[_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_6b031fcd0863e3f6b44230163f9] UNIQUE NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_9b7ca6d30b94fef571cff876884] UNIQUE NONCLUSTERED 
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[persons]    Script Date: 17/10/2020 5:16:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[persons](
	[_id] [int] IDENTITY(1,1) NOT NULL,
	[id] [nvarchar](10) NOT NULL,
	[givenName] [nvarchar](20) NOT NULL,
	[surname] [nvarchar](20) NOT NULL,
	[born] [int] NULL,
	[phone] [nvarchar](20) NULL,
	[email] [nvarchar](20) NULL,
	[address] [nvarchar](50) NULL,
 CONSTRAINT [PK_629035ac00fc23f7128b3cac482] PRIMARY KEY CLUSTERED 
(
	[_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_74278d8812a049233ce41440ac7] UNIQUE NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[relations]    Script Date: 17/10/2020 5:16:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[relations](
	[id] [nvarchar](10) NOT NULL,
	[p1_id] [int] NULL,
	[p2_id] [int] NULL,
	[kind] [nvarchar](15) NOT NULL,
	[since] [int] NULL,
	[_id] [int] IDENTITY(1,1) NOT NULL,
	[notes] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_1c71dec1293c43d448791e4c625] PRIMARY KEY CLUSTERED 
(
	[_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_5213edda543307fbe02cf3f3362] UNIQUE NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[roles]    Script Date: 17/10/2020 5:16:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[roles](
	[_id] [int] IDENTITY(1,1) NOT NULL,
	[id] [nvarchar](10) NOT NULL,
	[name] [nvarchar](30) NOT NULL,
	[description] [nvarchar](50) NULL,
 CONSTRAINT [PK_5e4c3ae73ef847866ca31d5e0f4] PRIMARY KEY CLUSTERED 
(
	[_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_648e3f5447f725579d7d4ffdfb7] UNIQUE NONCLUSTERED 
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_c1433d71a4838793a49dcad46ab] UNIQUE NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[users]    Script Date: 17/10/2020 5:16:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[_id] [int] NOT NULL,
	[id] [nvarchar](10) NOT NULL,
	[userName] [nvarchar](20) NOT NULL,
	[password] [nvarchar](20) NOT NULL,
	[permissions] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_users] PRIMARY KEY CLUSTERED 
(
	[_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[affiliations]  WITH CHECK ADD  CONSTRAINT [FK_31b6a301bddca48bfef7337b531] FOREIGN KEY([person_id])
REFERENCES [dbo].[persons] ([_id])
GO
ALTER TABLE [dbo].[affiliations] CHECK CONSTRAINT [FK_31b6a301bddca48bfef7337b531]
GO
ALTER TABLE [dbo].[affiliations]  WITH CHECK ADD  CONSTRAINT [FK_60f76de11e913da7f782b2f100e] FOREIGN KEY([organization_id])
REFERENCES [dbo].[organizations] ([_id])
GO
ALTER TABLE [dbo].[affiliations] CHECK CONSTRAINT [FK_60f76de11e913da7f782b2f100e]
GO
ALTER TABLE [dbo].[affiliations]  WITH CHECK ADD  CONSTRAINT [FK_89ecd08c20174082ea11dde7948] FOREIGN KEY([role_id])
REFERENCES [dbo].[roles] ([_id])
GO
ALTER TABLE [dbo].[affiliations] CHECK CONSTRAINT [FK_89ecd08c20174082ea11dde7948]
GO
ALTER TABLE [dbo].[organizations]  WITH CHECK ADD  CONSTRAINT [FK_f3a7c9411eaa5f9cbc5363de331] FOREIGN KEY([parent_id])
REFERENCES [dbo].[organizations] ([_id])
GO
ALTER TABLE [dbo].[organizations] CHECK CONSTRAINT [FK_f3a7c9411eaa5f9cbc5363de331]
GO
ALTER TABLE [dbo].[relations]  WITH CHECK ADD  CONSTRAINT [FK_21425c4cac370cf12b548b3c4bb] FOREIGN KEY([p2_id])
REFERENCES [dbo].[persons] ([_id])
GO
ALTER TABLE [dbo].[relations] CHECK CONSTRAINT [FK_21425c4cac370cf12b548b3c4bb]
GO
ALTER TABLE [dbo].[relations]  WITH CHECK ADD  CONSTRAINT [FK_c7c27a9acde7d9ecc2811af117c] FOREIGN KEY([p1_id])
REFERENCES [dbo].[persons] ([_id])
GO
ALTER TABLE [dbo].[relations] CHECK CONSTRAINT [FK_c7c27a9acde7d9ecc2811af117c]
GO
USE [master]
GO
ALTER DATABASE [PeopleDb] SET  READ_WRITE 
GO
